version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      PGSSLMODE: disable
      REDIS_URL: ${REDIS_URL}
      URL: ${URL}
      PORT: ${PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
volumes:
  storage-data:
